---
- name: Set timezone
  become: true
  community.general.timezone:
    name: "{{ timezone }}"

- name: Install gpg
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 00
    state: present
    pkg:
      - gpg

- name: Add an Apt signing key, uses whichever key is at the URL
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install OS Dependencies
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 00
    state: present
    pkg:
      - wget
      - unzip
      - apt-transport-https
      - ca-certificates
      - gpg
      - curl
      - gnupg
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-docker
      - python3-distutils

- name: adding user to docker group
  become: true
  ansible.builtin.user:
    name: tf2server
    groups: docker
    append: true

- name: Download Node Exporter
  become: true
  become_user: tf2server
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
    dest: ~/
    remote_src: true
    creates: node_exporter-1.1.2

- name: Extract Node Exporter
  become: true
  become_user: tf2server
  ansible.builtin.command:
    cmd: cp ~/node_exporter-1.1.2.linux-amd64/node_exporter ~/node_exporter
    creates: ~/node_exporter

- name: Create prometheus.service
  become: true
  ansible.builtin.copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: "644"

- name: mkdir gbans
  become: true
  become_user: tf2server
  ansible.builtin.file:
    path: ~/gbans
    state: directory
    mode: "0755"

- name: gbans download
  become: true
  become_user: tf2server
  ansible.builtin.unarchive:
    src: https://github.com/leighmacdonald/gbans/releases/download/v0.1.5/gbans--lin64.zip
    dest: ~/gbans
    remote_src: true

- name: gbans-relay.service
  become: true
  ansible.builtin.template:
    src: gbans-relay.service.j2
    dest: /etc/systemd/system/gbans-relay.service
    mode: "644"

- name: gbans chmod
  ansible.builtin.file:
    path: /home/tf2server/gbans/gbans
    mode: 0755

- name: gbans.yml
  become: true
  ansible.builtin.template:
    src: gbans.yml.j2
    dest: /home/tf2server/gbans.yml
    mode: "644"

- name: Enable TCP docker listener
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/systemd/system/multi-user.target.wants/docker.service
    regexp: '^ExecStart='
    line: "ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock"
    state: present
    backup: true

- name: systemd reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: systemd enable docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: systemd enable prometheus
  become: true
  ansible.builtin.systemd:
    name: node_exporter.service
    state: started
    enabled: true

- name: systemd enable gbans-relay
  become: true
  ansible.builtin.systemd:
    name: gbans-relay.service
    enabled: false
    state: stopped

- name: Increase available memory for UDP receive buffers
  become: true
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: "26214400"
    sysctl_set: true
    reload: true

- name: Increase available memory for UDP send buffers
  become: true
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: "26214400"
    sysctl_set: true
    reload: true

- name: Increase the maximum amount of packages in the kernel queue
  become: true
  ansible.posix.sysctl:
    name: net.core.netdev_max_backlog
    value: "25000"
    sysctl_set: true
    reload: true

- name: fw-docker
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    from_ip: "{{ docker_host_master }}"
  with_items:
    - "2000"

- name: fw-prom
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    from_ip: "{{ prometheus_host }}"
  with_items:
    - "9100"

- name: Enable UFW
  become: true
  community.general.ufw:
    state: reloaded
    policy: deny
